/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_hal.h"

static const char* CMockString_hal_get_ticks = "hal_get_ticks";
static const char* CMockString_hal_init = "hal_init";

typedef struct _CMOCK_hal_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_hal_init_CALL_INSTANCE;

typedef struct _CMOCK_hal_get_ticks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_hal_get_ticks_CALL_INSTANCE;

static struct mock_halInstance
{
  char hal_init_IgnoreBool;
  char hal_init_CallbackBool;
  CMOCK_hal_init_CALLBACK hal_init_CallbackFunctionPointer;
  int hal_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_init_CallInstance;
  char hal_get_ticks_IgnoreBool;
  uint32_t hal_get_ticks_FinalReturn;
  char hal_get_ticks_CallbackBool;
  CMOCK_hal_get_ticks_CALLBACK hal_get_ticks_CallbackFunctionPointer;
  int hal_get_ticks_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_get_ticks_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_hal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.hal_init_CallInstance;
  if (Mock.hal_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_get_ticks_CallInstance;
  if (Mock.hal_get_ticks_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_get_ticks);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_get_ticks_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_hal_Init(void)
{
  mock_hal_Destroy();
}

void mock_hal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void hal_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_init);
  cmock_call_instance = (CMOCK_hal_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_init_CallInstance);
  Mock.hal_init_CallInstance = CMock_Guts_MemNext(Mock.hal_init_CallInstance);
  if (Mock.hal_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_init_CallbackBool &&
      Mock.hal_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_init_CallbackFunctionPointer(Mock.hal_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.hal_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_init_CallbackFunctionPointer(Mock.hal_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void hal_init_CMockIgnore(void)
{
  Mock.hal_init_IgnoreBool = (char)1;
}

void hal_init_CMockStopIgnore(void)
{
  Mock.hal_init_IgnoreBool = (char)0;
}

void hal_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_init_CALL_INSTANCE));
  CMOCK_hal_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_init_CallInstance = CMock_Guts_MemChain(Mock.hal_init_CallInstance, cmock_guts_index);
  Mock.hal_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void hal_init_AddCallback(CMOCK_hal_init_CALLBACK Callback)
{
  Mock.hal_init_IgnoreBool = (char)0;
  Mock.hal_init_CallbackBool = (char)1;
  Mock.hal_init_CallbackFunctionPointer = Callback;
}

void hal_init_Stub(CMOCK_hal_init_CALLBACK Callback)
{
  Mock.hal_init_IgnoreBool = (char)0;
  Mock.hal_init_CallbackBool = (char)0;
  Mock.hal_init_CallbackFunctionPointer = Callback;
}

uint32_t hal_get_ticks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_get_ticks_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_get_ticks);
  cmock_call_instance = (CMOCK_hal_get_ticks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_get_ticks_CallInstance);
  Mock.hal_get_ticks_CallInstance = CMock_Guts_MemNext(Mock.hal_get_ticks_CallInstance);
  if (Mock.hal_get_ticks_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_get_ticks_FinalReturn;
    Mock.hal_get_ticks_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_get_ticks_CallbackBool &&
      Mock.hal_get_ticks_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.hal_get_ticks_CallbackFunctionPointer(Mock.hal_get_ticks_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.hal_get_ticks_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_get_ticks_CallbackFunctionPointer(Mock.hal_get_ticks_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void hal_get_ticks_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_get_ticks_CALL_INSTANCE));
  CMOCK_hal_get_ticks_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_get_ticks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_get_ticks_CallInstance = CMock_Guts_MemChain(Mock.hal_get_ticks_CallInstance, cmock_guts_index);
  Mock.hal_get_ticks_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_get_ticks_IgnoreBool = (char)1;
}

void hal_get_ticks_CMockStopIgnore(void)
{
  if(Mock.hal_get_ticks_IgnoreBool)
    Mock.hal_get_ticks_CallInstance = CMock_Guts_MemNext(Mock.hal_get_ticks_CallInstance);
  Mock.hal_get_ticks_IgnoreBool = (char)0;
}

void hal_get_ticks_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_get_ticks_CALL_INSTANCE));
  CMOCK_hal_get_ticks_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_get_ticks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_get_ticks_CallInstance = CMock_Guts_MemChain(Mock.hal_get_ticks_CallInstance, cmock_guts_index);
  Mock.hal_get_ticks_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void hal_get_ticks_AddCallback(CMOCK_hal_get_ticks_CALLBACK Callback)
{
  Mock.hal_get_ticks_IgnoreBool = (char)0;
  Mock.hal_get_ticks_CallbackBool = (char)1;
  Mock.hal_get_ticks_CallbackFunctionPointer = Callback;
}

void hal_get_ticks_Stub(CMOCK_hal_get_ticks_CALLBACK Callback)
{
  Mock.hal_get_ticks_IgnoreBool = (char)0;
  Mock.hal_get_ticks_CallbackBool = (char)0;
  Mock.hal_get_ticks_CallbackFunctionPointer = Callback;
}

