/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_delay.h"

static const char* CMockString_delay = "delay";
static const char* CMockString_delay_get_status = "delay_get_status";
static const char* CMockString_delay_init = "delay_init";
static const char* CMockString_delay_reset = "delay_reset";
static const char* CMockString_duration = "duration";

typedef struct _CMOCK_delay_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  delay_ret_t ReturnVal;
  int CallOrder;
  delay_t* Expected_delay;
  uint32_t Expected_duration;

} CMOCK_delay_init_CALL_INSTANCE;

typedef struct _CMOCK_delay_get_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  delay_ret_t ReturnVal;
  int CallOrder;
  delay_t* Expected_delay;

} CMOCK_delay_get_status_CALL_INSTANCE;

typedef struct _CMOCK_delay_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  delay_ret_t ReturnVal;
  int CallOrder;
  delay_t* Expected_delay;

} CMOCK_delay_reset_CALL_INSTANCE;

static struct mock_delayInstance
{
  char delay_init_IgnoreBool;
  delay_ret_t delay_init_FinalReturn;
  char delay_init_CallbackBool;
  CMOCK_delay_init_CALLBACK delay_init_CallbackFunctionPointer;
  int delay_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE delay_init_CallInstance;
  char delay_get_status_IgnoreBool;
  delay_ret_t delay_get_status_FinalReturn;
  char delay_get_status_CallbackBool;
  CMOCK_delay_get_status_CALLBACK delay_get_status_CallbackFunctionPointer;
  int delay_get_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE delay_get_status_CallInstance;
  char delay_reset_IgnoreBool;
  delay_ret_t delay_reset_FinalReturn;
  char delay_reset_CallbackBool;
  CMOCK_delay_reset_CALLBACK delay_reset_CallbackFunctionPointer;
  int delay_reset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE delay_reset_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_delay_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.delay_init_CallInstance;
  if (Mock.delay_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_delay_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.delay_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.delay_get_status_CallInstance;
  if (Mock.delay_get_status_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_delay_get_status);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.delay_get_status_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.delay_reset_CallInstance;
  if (Mock.delay_reset_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_delay_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.delay_reset_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_delay_Init(void)
{
  mock_delay_Destroy();
}

void mock_delay_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

delay_ret_t delay_init(delay_t* delay, uint32_t duration)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_delay_init);
  cmock_call_instance = (CMOCK_delay_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.delay_init_CallInstance);
  Mock.delay_init_CallInstance = CMock_Guts_MemNext(Mock.delay_init_CallInstance);
  if (Mock.delay_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.delay_init_FinalReturn;
    memcpy((void*)(&Mock.delay_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(delay_ret_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.delay_init_CallbackBool &&
      Mock.delay_init_CallbackFunctionPointer != NULL)
  {
    delay_ret_t cmock_cb_ret = Mock.delay_init_CallbackFunctionPointer(delay, duration, Mock.delay_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_delay_init,CMockString_delay);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_delay), (void*)(delay), sizeof(delay_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_delay_init,CMockString_duration);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_duration, duration, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.delay_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.delay_init_CallbackFunctionPointer(delay, duration, Mock.delay_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_delay_init(CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance, delay_t* delay, uint32_t duration);
void CMockExpectParameters_delay_init(CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance, delay_t* delay, uint32_t duration)
{
  cmock_call_instance->Expected_delay = delay;
  cmock_call_instance->Expected_duration = duration;
}

void delay_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_init_CALL_INSTANCE));
  CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_init_CallInstance = CMock_Guts_MemChain(Mock.delay_init_CallInstance, cmock_guts_index);
  Mock.delay_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.delay_init_IgnoreBool = (char)1;
}

void delay_init_CMockStopIgnore(void)
{
  if(Mock.delay_init_IgnoreBool)
    Mock.delay_init_CallInstance = CMock_Guts_MemNext(Mock.delay_init_CallInstance);
  Mock.delay_init_IgnoreBool = (char)0;
}

void delay_init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_init_CALL_INSTANCE));
  CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_init_CallInstance = CMock_Guts_MemChain(Mock.delay_init_CallInstance, cmock_guts_index);
  Mock.delay_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void delay_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, delay_t* delay, uint32_t duration, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_init_CALL_INSTANCE));
  CMOCK_delay_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_init_CallInstance = CMock_Guts_MemChain(Mock.delay_init_CallInstance, cmock_guts_index);
  Mock.delay_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_delay_init(cmock_call_instance, delay, duration);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(delay_ret_t[sizeof(cmock_to_return) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
}

void delay_init_AddCallback(CMOCK_delay_init_CALLBACK Callback)
{
  Mock.delay_init_IgnoreBool = (char)0;
  Mock.delay_init_CallbackBool = (char)1;
  Mock.delay_init_CallbackFunctionPointer = Callback;
}

void delay_init_Stub(CMOCK_delay_init_CALLBACK Callback)
{
  Mock.delay_init_IgnoreBool = (char)0;
  Mock.delay_init_CallbackBool = (char)0;
  Mock.delay_init_CallbackFunctionPointer = Callback;
}

delay_ret_t delay_get_status(delay_t* delay)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_delay_get_status);
  cmock_call_instance = (CMOCK_delay_get_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.delay_get_status_CallInstance);
  Mock.delay_get_status_CallInstance = CMock_Guts_MemNext(Mock.delay_get_status_CallInstance);
  if (Mock.delay_get_status_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.delay_get_status_FinalReturn;
    memcpy((void*)(&Mock.delay_get_status_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(delay_ret_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.delay_get_status_CallbackBool &&
      Mock.delay_get_status_CallbackFunctionPointer != NULL)
  {
    delay_ret_t cmock_cb_ret = Mock.delay_get_status_CallbackFunctionPointer(delay, Mock.delay_get_status_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_delay_get_status,CMockString_delay);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_delay), (void*)(delay), sizeof(delay_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.delay_get_status_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.delay_get_status_CallbackFunctionPointer(delay, Mock.delay_get_status_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_delay_get_status(CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance, delay_t* delay);
void CMockExpectParameters_delay_get_status(CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance, delay_t* delay)
{
  cmock_call_instance->Expected_delay = delay;
}

void delay_get_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_get_status_CALL_INSTANCE));
  CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_get_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_get_status_CallInstance = CMock_Guts_MemChain(Mock.delay_get_status_CallInstance, cmock_guts_index);
  Mock.delay_get_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.delay_get_status_IgnoreBool = (char)1;
}

void delay_get_status_CMockStopIgnore(void)
{
  if(Mock.delay_get_status_IgnoreBool)
    Mock.delay_get_status_CallInstance = CMock_Guts_MemNext(Mock.delay_get_status_CallInstance);
  Mock.delay_get_status_IgnoreBool = (char)0;
}

void delay_get_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_get_status_CALL_INSTANCE));
  CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_get_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_get_status_CallInstance = CMock_Guts_MemChain(Mock.delay_get_status_CallInstance, cmock_guts_index);
  Mock.delay_get_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void delay_get_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, delay_t* delay, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_get_status_CALL_INSTANCE));
  CMOCK_delay_get_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_get_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_get_status_CallInstance = CMock_Guts_MemChain(Mock.delay_get_status_CallInstance, cmock_guts_index);
  Mock.delay_get_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_delay_get_status(cmock_call_instance, delay);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(delay_ret_t[sizeof(cmock_to_return) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
}

void delay_get_status_AddCallback(CMOCK_delay_get_status_CALLBACK Callback)
{
  Mock.delay_get_status_IgnoreBool = (char)0;
  Mock.delay_get_status_CallbackBool = (char)1;
  Mock.delay_get_status_CallbackFunctionPointer = Callback;
}

void delay_get_status_Stub(CMOCK_delay_get_status_CALLBACK Callback)
{
  Mock.delay_get_status_IgnoreBool = (char)0;
  Mock.delay_get_status_CallbackBool = (char)0;
  Mock.delay_get_status_CallbackFunctionPointer = Callback;
}

delay_ret_t delay_reset(delay_t* delay)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_delay_reset);
  cmock_call_instance = (CMOCK_delay_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.delay_reset_CallInstance);
  Mock.delay_reset_CallInstance = CMock_Guts_MemNext(Mock.delay_reset_CallInstance);
  if (Mock.delay_reset_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.delay_reset_FinalReturn;
    memcpy((void*)(&Mock.delay_reset_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(delay_ret_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.delay_reset_CallbackBool &&
      Mock.delay_reset_CallbackFunctionPointer != NULL)
  {
    delay_ret_t cmock_cb_ret = Mock.delay_reset_CallbackFunctionPointer(delay, Mock.delay_reset_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_delay_reset,CMockString_delay);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_delay), (void*)(delay), sizeof(delay_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.delay_reset_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.delay_reset_CallbackFunctionPointer(delay, Mock.delay_reset_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_delay_reset(CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance, delay_t* delay);
void CMockExpectParameters_delay_reset(CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance, delay_t* delay)
{
  cmock_call_instance->Expected_delay = delay;
}

void delay_reset_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_reset_CALL_INSTANCE));
  CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_reset_CallInstance = CMock_Guts_MemChain(Mock.delay_reset_CallInstance, cmock_guts_index);
  Mock.delay_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.delay_reset_IgnoreBool = (char)1;
}

void delay_reset_CMockStopIgnore(void)
{
  if(Mock.delay_reset_IgnoreBool)
    Mock.delay_reset_CallInstance = CMock_Guts_MemNext(Mock.delay_reset_CallInstance);
  Mock.delay_reset_IgnoreBool = (char)0;
}

void delay_reset_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_reset_CALL_INSTANCE));
  CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_reset_CallInstance = CMock_Guts_MemChain(Mock.delay_reset_CallInstance, cmock_guts_index);
  Mock.delay_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void delay_reset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, delay_t* delay, delay_ret_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_reset_CALL_INSTANCE));
  CMOCK_delay_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_reset_CallInstance = CMock_Guts_MemChain(Mock.delay_reset_CallInstance, cmock_guts_index);
  Mock.delay_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_delay_reset(cmock_call_instance, delay);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(delay_ret_t[sizeof(cmock_to_return) == sizeof(delay_ret_t) ? 1 : -1])); /* add delay_ret_t to :treat_as_array if this causes an error */
}

void delay_reset_AddCallback(CMOCK_delay_reset_CALLBACK Callback)
{
  Mock.delay_reset_IgnoreBool = (char)0;
  Mock.delay_reset_CallbackBool = (char)1;
  Mock.delay_reset_CallbackFunctionPointer = Callback;
}

void delay_reset_Stub(CMOCK_delay_reset_CALLBACK Callback)
{
  Mock.delay_reset_IgnoreBool = (char)0;
  Mock.delay_reset_CallbackBool = (char)0;
  Mock.delay_reset_CallbackFunctionPointer = Callback;
}

