pipeline {
    agent any 

    environment {
        TOOL_DIR = "${WORKSPACE}\\ci-cd-tools"
    }

    stages {
        stage('Build') { 
            steps {
				sh 'echo Comenzando Build'
				sh 'make -C src/ci-cd-tools/ clean'
				sh 'make -C src/ci-cd-tools/ -j8 all'
				status = findText(textFinders: [
				  textFinder(regexp: 'warning', alsoCheckConsoleOutput: true, buildResult: 'UNSTABLE')
				])
				echo status
            }
        }
        stage('Static Analysis') { 
            steps {
				sh 'echo Comenzando Cpp-Check'
            }
        }
    }

    post {
        success {
			sh 'echo success'
        }
        unsuccessful {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "Unsuccessful build ${env.BUILD_ID}",
                    body: "Build ${env.BUILD_ID} has result ${currentBuild.currentResult}"
                )
            }
        }
    }
}