/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "mock_delay.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test__dictionary_init__init(void);
extern void test__dictionary_init__write_int_value_valid_index(void);
extern void test__dictionary_init__write_int_value_invalid_index(void);
extern void test__dictionary_init__read_int_value_invalid_index(void);
extern void test__dictionary_init__read_int_value_valid_index_no_expired(void);
extern void test__dictionary_init__read_int_value_valid_index_expired(void);
extern void test__dictionary_init__read_int_value_valid_index_no_expiration(void);
extern void test__dictionary_init__read_int_value_valid_index_source(void);
extern void test__dictionary_init__read_neg_int_value_valid_index_no_expired(void);
extern void test__dictionary_init__write_float_value_valid_index(void);
extern void test__dictionary_init__write_float_value_invalid_index(void);
extern void test__dictionary_init__read_float_value_invalid_index(void);
extern void test__dictionary_init__read_float_value_valid_index_no_expired(void);
extern void test__dictionary_init__read_float_value_valid_index_expired(void);
extern void test__dictionary_init__read_float_value_valid_index_no_expiration(void);
extern void test__dictionary_init__read_float_value_valid_index_source(void);
extern void test__dictionary_init__read_neg_float_value_valid_index_no_expired(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_delay_Init();
}
static void CMock_Verify(void)
{
  mock_delay_Verify();
}
static void CMock_Destroy(void)
{
  mock_delay_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_dictionary.c");
  run_test(test__dictionary_init__init, "test__dictionary_init__init", 27);
  run_test(test__dictionary_init__write_int_value_valid_index, "test__dictionary_init__write_int_value_valid_index", 50);
  run_test(test__dictionary_init__write_int_value_invalid_index, "test__dictionary_init__write_int_value_invalid_index", 77);
  run_test(test__dictionary_init__read_int_value_invalid_index, "test__dictionary_init__read_int_value_invalid_index", 104);
  run_test(test__dictionary_init__read_int_value_valid_index_no_expired, "test__dictionary_init__read_int_value_valid_index_no_expired", 125);
  run_test(test__dictionary_init__read_int_value_valid_index_expired, "test__dictionary_init__read_int_value_valid_index_expired", 159);
  run_test(test__dictionary_init__read_int_value_valid_index_no_expiration, "test__dictionary_init__read_int_value_valid_index_no_expiration", 194);
  run_test(test__dictionary_init__read_int_value_valid_index_source, "test__dictionary_init__read_int_value_valid_index_source", 229);
  run_test(test__dictionary_init__read_neg_int_value_valid_index_no_expired, "test__dictionary_init__read_neg_int_value_valid_index_no_expired", 265);
  run_test(test__dictionary_init__write_float_value_valid_index, "test__dictionary_init__write_float_value_valid_index", 303);
  run_test(test__dictionary_init__write_float_value_invalid_index, "test__dictionary_init__write_float_value_invalid_index", 330);
  run_test(test__dictionary_init__read_float_value_invalid_index, "test__dictionary_init__read_float_value_invalid_index", 357);
  run_test(test__dictionary_init__read_float_value_valid_index_no_expired, "test__dictionary_init__read_float_value_valid_index_no_expired", 378);
  run_test(test__dictionary_init__read_float_value_valid_index_expired, "test__dictionary_init__read_float_value_valid_index_expired", 412);
  run_test(test__dictionary_init__read_float_value_valid_index_no_expiration, "test__dictionary_init__read_float_value_valid_index_no_expiration", 448);
  run_test(test__dictionary_init__read_float_value_valid_index_source, "test__dictionary_init__read_float_value_valid_index_source", 483);
  run_test(test__dictionary_init__read_neg_float_value_valid_index_no_expired, "test__dictionary_init__read_neg_float_value_valid_index_no_expired", 519);

  CMock_Guts_MemFreeFinal();
  return UnityEnd();
}
