/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "mock_hal.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test__delay_init__null_instance(void);
extern void test__delay_init__randon_duration(void);
extern void test__delay_get_status__null_instance(void);
extern void test__delay_get_status__delay_running(void);
extern void test__delay_get_status__delay_expired(void);
extern void test__delay_reset__null_instance(void);
extern void test__delay_reset__reset(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_hal_Init();
}
static void CMock_Verify(void)
{
  mock_hal_Verify();
}
static void CMock_Destroy(void)
{
  mock_hal_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_delay.c");
  run_test(test__delay_init__null_instance, "test__delay_init__null_instance", 30);
  run_test(test__delay_init__randon_duration, "test__delay_init__randon_duration", 56);
  run_test(test__delay_get_status__null_instance, "test__delay_get_status__null_instance", 98);
  run_test(test__delay_get_status__delay_running, "test__delay_get_status__delay_running", 122);
  run_test(test__delay_get_status__delay_expired, "test__delay_get_status__delay_expired", 162);
  run_test(test__delay_reset__null_instance, "test__delay_reset__null_instance", 202);
  run_test(test__delay_reset__reset, "test__delay_reset__reset", 226);

  CMock_Guts_MemFreeFinal();
  return UnityEnd();
}
